""""""""""""""""""""""""""""""""""
" P-Miranda's .vimrc
""""""""""""""""""""""""""""""""""
" Note: vimrc existence already triggers nocompatible by default
" map leader key needs to be defined before <leader> mappings
let mapleader = ' ' 
""""""""""""""""""""""""""""""""""
" Plugins managed by Vundle [git@github.com:VundleVim/Vundle.vim.git]
""""""""""""""""""""""""""""""""""
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Vundle manages itself, required
Plugin 'VundleVim/Vundle.vim'

" My custom plugins
Plugin 'morhetz/gruvbox' " color scheme
Plugin 'tpope/vim-commentary' " Command to toggle comments <gc>
Plugin 'tpope/vim-fugitive' " Git wrapper for vim. Prefix :G
" add more plugins here
call vundle#end()
filetype plugin indent on

" vim-fugitive 
" delete fugitive buffers automatically
autocmd BufReadPost fugitive://* set bufhidden=delete
""""""""""""""""""""""""""""""""""
" Theme gruvbox [github.com:morhetz/gruvbox.git]
""""""""""""""""""""""""""""""""""
autocmd vimenter * nested colorscheme gruvbox
set background=dark " Setting dark mode
""""""""""""""""""""""""""""""""""
" Custom Comments for Filetypes
""""""""""""""""""""""""""""""""""
autocmd Filetype octave setlocal commentstring=%\ %s
""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""
" Misc
set backspace=indent,eol,start " expected backspace behaviour with identation
set hidden " enable switching from non-saved buffers
set lazyredraw " don't redraw while executing macros and non-typed commands

" Appearance
syntax on " highlight syntax
set number " show line numbers
set showcmd " Show partial command on bottom-right
set wrap " Wrap long text lines
set cursorline " highlight current line
set showmatch " highlight matching {[()]}
set scrolloff=10 "always show X lines above and below cursor line
set splitright "open new vertical splits on the right
set splitbelow "open new horizontal splits below
set textwidth=0 "do not wrap text after column 80 by default
set colorcolumn=80 " color column on 80th column
highlight ColorColumn ctermbg=0 guibg=lightgrey
set breakindent " wrapped lines keep same indentation

" status line
set statusline=
set statusline+=%f " relative filepath from current working directory
set statusline+=%m%r%w " modified, readonly, preview flags
set statusline+=%{FugitiveStatusline()} " display git branch (vim-fugitive)
set statusline+=%= " align items to the right after this point
set statusline+=[%{&ff}]%y " current filetype and syntax
set statusline+=[%p%%/%LL][%l,%c] " lines %, total lines, current line and col
set laststatus=2 " always show status bar

" command completion
set wildmenu " show vim command completion options
set wildmode=longest:full,full " choose longest matching option first
set wildignorecase " ignore cases when matching commands
" tell vim you never want to edit these files
set wildignore+=*.~,*.swp
set wildignore+=*.pyc,*.o,*.a,*.so
set wildignore+=*.git/*


" search
set nohlsearch " no highlighting after search
set ignorecase " ignore case in search
set smartcase " don't ignore case if there is a capitalized letter in search
set incsearch " show search results as you type
set path+=** " find files in all subdirectories from $PWD

" tabs and spaces
" default configuration
set tabstop=4 "\t characters width measured in spaces
set shiftwidth=4 "identation width measured in spaces
set expandtab "expandtab: tabs are replaced by spaces*
set softtabstop=4 "tab or backspace keypress measured in spaces
set autoindent "Copy indent from current line when starting a new one
" indentation settings by filetype
" tipical tabs only
" autocmd FileType <FileType> setlocal tabstop=4 shiftwidth=4 noexpandtab autoindent
" tipical spaces only
" autocmd FileType <FileType> setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab autoindent
autocmd FileType make setlocal noexpandtab

" temp files
set backupdir=~/.vim/tmp// " file copy before vim edition
set directory=~/.vim/tmp// " unsaved changes
set undodir=~/.vim/tmp//   " undo tree of edited files
""""""""""""""""""""""""""""""""""
" Custom Mappings
""""""""""""""""""""""""""""""""""
" Press ii to exit insert mode -> normal mode
inoremap ii <ESC>
" Press ii to exit visual mode -> normal mode
vnoremap ii <ESC>
" Press ii to exit command mode -> normal mode
cnoremap ii <ESC>
" Open vimrc
nnoremap <leader>rc :e $MYVIMRC<CR>
" List and switch buffers
nnoremap <leader>b :ls<CR>:b<Space>*
" Find file in subdirectories
nnoremap <leader>f :find *
" External grep
nnoremap <leader>gr :gr<Space>-r<Space><Space>*<Left><Left>
" Y behaves like D and C
nnoremap Y y$
" Keep searches centered zz centers cursor line
nnoremap n nzz
nnoremap N Nzz
" Moving text
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
" Better tabs: gv re-selects text automatically
vnoremap > >gv
vnoremap < <gv
""""""""""""""""""""""""""""""""""
" Filetype Syntax Highlighting
""""""""""""""""""""""""""""""""""
augroup filetypedetect
	au! BufRead,BufNewFile *.m,*.oct set filetype=octave
	au! BufRead,BufNewFile *.vh,*.sv set filetype=verilog
augroup END
