""""""""""""""""""""""""""""""""""
" P-Miranda's .vimrc
""""""""""""""""""""""""""""""""""
" map leader key needs to be defined before <leader> mappings
let mapleader = ' ' 
""""""""""""""""""""""""""""""""""
" Plugins managed by Vundle [git@github.com:VundleVim/Vundle.vim.git]
""""""""""""""""""""""""""""""""""
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" Vundle manages itself, required
Plugin 'VundleVim/Vundle.vim'

" My custom plugins
Plugin 'morhetz/gruvbox' " color scheme
Plugin 'tpope/vim-commentary' " Command to toggle comments <gc>
" add more plugins here
call vundle#end()
filetype plugin indent on

""""""""""""""""""""""""""""""""""
" Theme gruvbox [github.com:morhetz/gruvbox.git]
""""""""""""""""""""""""""""""""""
autocmd vimenter * nested colorscheme gruvbox
set background=dark " Setting dark mode
""""""""""""""""""""""""""""""""""
" Custom Comments for Filetypes
""""""""""""""""""""""""""""""""""
autocmd Filetype octave setlocal commentstring=%\ %s
""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""
" Appearance
syntax on " highlight syntax
set number " show line numbers
set showcmd " Show partial command on bottom-right
set wrap " Wrap long text lines
set cursorline " highlight current line
set showmatch " highlight matching {[()]}
set scrolloff=10 "always show X lines above and below cursor line
set splitright "open new vertical splits on the right
set splitbelow "open new horizontal splits below
set textwidth=0 "do not wrap text after column 80 by default
set colorcolumn=80 " color column on 80th column
highlight ColorColumn ctermbg=0 guibg=lightgrey
set breakindent " wrapped lines keep same indentation

" status line
set statusline=
set statusline+=%f " relative filepath from current working directory
set statusline+=%m%r%w " modified, readonly, preview flags
set statusline+=%= " align items to the right after this point
set statusline+=[%{&ff}]%y " current filetype and syntax
set statusline+=[%p%%/%LL][%l,%c] " lines %, total lines, current line and col
set laststatus=2 " always show status bar

" command completion
set wildmenu " show vim command completion options
set wildmode=longest:full,full " choose longest matching option first
set wildignorecase " ignore cases when matching commands
" tell vim you never want to edit these files
set wildignore+=*.~,*.swp
set wildignore+=*.pyc,*.o,*.a,*.so
set wildignore+=*.git/*


" search
set nohlsearch " no highlighting after search
set ignorecase " ignore case in search
set incsearch " show search results as you type

" tabs and spaces
" default configuration
set tabstop=4 "\t characters width measured in spaces
set shiftwidth=4 "identation width measured in spaces
set expandtab "expandtab: tabs are replaced by spaces*
set softtabstop=4 "tab or backspace keypress measured in spaces
set autoindent "Copy indent from current line when starting a new one
" indentation settings by filetype
" tipical tabs only
" autocmd FileType <FileType> setlocal tabstop=4 shiftwidth=4 noexpandtab autoindent
" tipical spaces only
" autocmd FileType <FileType> setlocal tabstop=4 shiftwidth=4 softtabstop=4 expandtab autoindent
autocmd FileType make setlocal noexpandtab

" temp files
set backupdir=~/.vim/tmp// " file copy before vim edition
set directory=~/.vim/tmp// " unsaved changes
set undodir=~/.vim/tmp//   " undo tree of edited files
""""""""""""""""""""""""""""""""""
" Custom Mappings
""""""""""""""""""""""""""""""""""
" Press ii to exit insert mode -> normal mode
inoremap ii <ESC>
" Press ii to exit visual mode -> normal mode
vnoremap ii <ESC>
" Press ii to exit command mode -> normal mode
cnoremap ii <ESC>
""""""""""""""""""""""""""""""""""
" Filetype Syntax Highlighting
""""""""""""""""""""""""""""""""""
augroup filetypedetect
	au! BufRead,BufNewFile *.m,*.oct set filetype=octave
	au! BufRead,BufNewFile *.vh,*.sv set filetype=verilog
augroup END
